spring.application.name=telecomcrm
spring.config.import=optional:file:.env[.properties]

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=${DATABASE_CONNECTION_TIMEOUT:15000}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.cache.type=redis
spring.cache.redis.time-to-live=5m
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_TIMEOUT:2s}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=telecom-crm-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.enes.telecomcrm.*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
app.kafka.topics.ticket-created=ticket-created
app.kafka.topics.ticket-resolved=ticket-resolved
app.kafka.topics.subscription-activated=subscription-activated

spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME:}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD:}
spring.elasticsearch.connection-timeout=${ELASTICSEARCH_CONNECTION_TIMEOUT:2s}
spring.elasticsearch.socket-timeout=${ELASTICSEARCH_SOCKET_TIMEOUT:5s}
app.elasticsearch.indexes.tickets=tickets
app.elasticsearch.indexes.users=users
